### PR TITLE
Split the core

### PR DESCRIPTION
**Pull request by Hywan**
Address https://github.com/hoaproject/Core/issues/96.

The core is being splitted into several libraries. `Hoa\Event` is one of them.

### CODE REVIEW

**Comment by shulard** [comment]
Do you think that `composer.json` must be updated to require `hoa/event` directly ? 

Personally, I prefer to have direct dependencies declared in `composer.json`.

**Comment by Hywan** [comment]
@shulard No because we are not using it directly. This is like interface, we do not require them, we just “use” them as type-hint, no instance. Thoughts?

**Comment by shulard** [comment]
@hywan, yes but if you use the `Hoa\Event\Bucket` even only for type hint it must be loaded. I think that with that update you can't use `hoa/devtools` without requiring `hoa/event`.

**Comment by Hywan** [comment]
@shulard If your code works, it means that `Hoa\Event` exists somewhere else (at least from the source of the event), so it is actually somewhere.

**Comment by shulard** [comment]
Ok, I understand because we rely on `Console\Processus` and the `hoa/event` is loaded with `hoa/console` so it's ok...
You're right, in that case we are "just" implementing a `Processus` object. Thanks for the clarification :smile:

**Comment by Hywan** [comment]
Correct!

**Pull request merged**
