### PR TITLE
Add Zsh autocompletion for `hoa`

### PR DESCRIPTION
**Pull request by Hywan**
Thoughts?

### CODE REVIEW

**Comment by Hywan** [comment]
ping @vonglasow

**Comment by vonglasow** [comment]
:+1: yeah it works well ;) thanks :D

**Comment by Hywan** [comment]
We do not support argument so far. Any idea how?

**Comment by vonglasow** [comment]
@Hywan idea to support argument see https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/phing/phing.plugin.zsh

**Comment by Hywan** [comment]
@vonglasow Huh?

**Comment by vonglasow** [comment]
It's an example how oh-my-zsh support arguments with the tool phing maybe we can be inspired from it.

**Comment by Hywan** [comment]
@vonglasow The difficulty is not to support arguments autocompletion in Zsh but how to extract them from a script ;-).

**Pull request merged**
