### PR TITLE
Merge `Hoathis\Documentation` to `Hoa\Devtools`

### LINKED ISSUE #14: Merge Hoathis\Documentation into Hoa\Devtools
Hello :smiley:,

I was thinking about simplifying the contribution process and thought: What about merging the [the `Hoathis\Documentation` tool](https://github.com/hoaproject/Hoathis-Documentation) into this library. For me it makes sense:
- Less repository to maintain (which is good!),
- One place for all devtools,
- Ease the contribution (you install `hoa/test` which install `hoa/devtools` and here you go, or you install `hoa/devtools` and here you go).

Thoughts @hoaproject/hoackers?

### PR DESCRIPTION
**Pull request by Hywan**
Fix #14.

Progression:
- [x] Merge `Hoathis\Documentation`,
- [x] Close `Hoathis\Documentation` (and mirrors).

### CODE REVIEW

**Comment by Hywan** [comment]
If `Hoa\Devtools` is installed through Composer, it only generates documentation of the sibling library, not the one from the “current”/“targeted” library. I will fix this tomorrow morning on the train, then squash and @osaris will be able to make a peer-review!

**Comment by Hywan** [comment]
@osaris Ready for a review :smile:!

**Comment by osaris** [comment]
Perfect ! Thx :)

**Comment by Hywan** [comment]
Removed from the website, from Git repositories and also mirrors.

Done!

**Pull request merged**
